const ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
  CHECKIN_STAFF: 'CHECKIN_STAFF'
};

const EVENT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  ARCHIVED: 'ARCHIVED'
};

const EVENT_CATEGORIES = [
  'General',
  'Running',
  'Motorsport',
  'Car Racing',
  'Bike Racing',
  'Cycling',
  'Sports',
  'Fitness',
  'College',
  'Corporate',
  'Community',
  'Other'
];

const REGISTRATION_STATUS = {
  PENDING: 'PENDING',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  CONFIRMED: 'CONFIRMED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
  WAITLISTED: 'WAITLISTED',
  CHECKED_IN: 'CHECKED_IN'
};

const PAYMENT_STATUS = {
  NOT_REQUIRED: 'NOT_REQUIRED',
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};

const PAYMENT_PROVIDERS = {
  RAZORPAY: 'RAZORPAY',
  STRIPE: 'STRIPE',
  MOCK: 'MOCK'
};

module.exports = {
  ROLES,
  EVENT_STATUS,
  EVENT_CATEGORIES,
  REGISTRATION_STATUS,
  PAYMENT_STATUS,
  PAYMENT_PROVIDERS
};
